name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: GitHub Action
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi Authorization_API.yaml --key=${{ secrets.README_FILES_AUTH_KEY }} --id=${{ secrets.README_FILES_AUTH_ID }}
          
      - name: GitHub Action
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_AMS_Report_API.yaml --key=${{ secrets.README_FILES_AUTH_KEY }} --id=${{ secrets.README_FILES_V1_AMS_REPORT_ID }}
        
      - name: GitHub Action
        uses: readmeio/rdme@8.0.4
        with:
          rdme: openapi V1_AMS_Report_Menu_API.yaml --key=${{ secrets.README_FILES_AUTH_KEY }} --id=${{ secrets.README_FILES_V1_AMS_REPORT_MENU_ID }}
